document.write('<script type="text/javascript" src="../bower_components/jquery/dist/jquery.js"></script>');  
document.write('<script type="text/javascript" src="lib/treeview/jquery.treeview.js"></script>');
document.write('<script type="text/javascript" src="../src/core/core.js"></script>');
document.write('<script type="text/javascript" src="../src/core/core_utils.js"></script>');
document.write('<script type="text/javascript" src="../src/xml/xml.js"></script>');
document.write('<script type="text/javascript" src="../src/wrapped_libs/wgxpath.js"></script>');  // XPAth fix
document.write('<script type="text/javascript" src="../src/wrapped_libs/json2.js"></script>');  // JSON fix
document.write('<script type="text/javascript" src="../src/data/data.js"></script>');
document.write('<script type="text/javascript" src="../src/usage/usage.js"></script>');
document.write('<script type="text/javascript" src="../src/usages/usages.js"></script>');
document.write('<script type="text/javascript" src="../src/aaeditor/bart_dt_usage.js"></script>');
document.write('<script type="text/javascript" src="../src/aaeditor/xtml_dt_usage.js"></script>');
document.write('<script type="text/javascript" src="../src/ui/ui_usage.js"></script>');
document.write('<script type="text/javascript" src="../src/yesno/yesno.js"></script>');
document.write('<script type="text/javascript" src="../src/yesno/yesno_usage.js"></script>');
document.write('<script type="text/javascript" src="../src/ui/ui.js"></script>');
document.write('<script type="text/javascript" src="../src/ui/graph.js"></script>');
document.write('<script type="text/javascript" src="../src/jbart/validations.js"></script>');
document.write('<script type="text/javascript" src="../src/jbart/jbart_general_utils.js"></script>');
document.write('<script type="text/javascript" src="../src/jbart/basefield.js"></script>');
document.write('<script type="text/javascript" src="../src/jbart/multi_picklist.js"></script>');
document.write('<script type="text/javascript" src="../src/jbart/transition.js"></script>');
document.write('<script type="text/javascript" src="../src/jbart/field.js"></script>');
document.write('<script type="text/javascript" src="../src/jbart/number.js"></script>');
document.write('<script type="text/javascript" src="../src/image/image.js"></script>');
document.write('<script type="text/javascript" src="../src/popup/popup.js"></script>');
document.write('<script type="text/javascript" src="../src/jbart/field_aspect.js"></script>');
document.write('<script type="text/javascript" src="../src/field/event_aspects.js"></script>');
document.write('<script type="text/javascript" src="../src/field/picklist.js"></script>');
document.write('<script type="text/javascript" src="../src/field/field_control.js"></script>');
document.write('<script type="text/javascript" src="../src/field/slider.js"></script>');
document.write('<script type="text/javascript" src="../src/ui/operation.js"></script>');
document.write('<script type="text/javascript" src="../src/ui/aspect_utils.js"></script>');
document.write('<script type="text/javascript" src="../src/control/image_gallery.js"></script>');
document.write('<script type="text/javascript" src="../src/control/propertysheet.js"></script>');
document.write('<script type="text/javascript" src="../src/control/searchbox.js"></script>');
document.write('<script type="text/javascript" src="../src/itemtree/itemtree.js"></script>');
document.write('<script type="text/javascript" src="../src/itemtree/xmltree.js"></script>');
document.write('<script type="text/javascript" src="../src/itemlist/itemlist.js"></script>');
document.write('<script type="text/javascript" src="../src/itemlist/itemlist_groups.js"></script>');
document.write('<script type="text/javascript" src="../src/itemlist/dragndrop.js"></script>');
document.write('<script type="text/javascript" src="../src/itemlist/dragdrop_items.js"></script>');
document.write('<script type="text/javascript" src="../src/itemtree/dragdrop_tree.js"></script>');
document.write('<script type="text/javascript" src="../src/ui/suggestbox.js"></script>');
document.write('<script type="text/javascript" src="../src/text/text.js"></script>');
document.write('<script type="text/javascript" src="../src/text/text_usage.js"></script>');
document.write('<script type="text/javascript" src="../src/date/date.js"></script>');
document.write('<script type="text/javascript" src="../src/debugui/debugui.js"></script>');
document.write('<script type="text/javascript" src="../src/xml/xml_usage.js"></script>');
document.write('<script type="text/javascript" src="../src/data/object.js"></script>');
document.write('<script type="text/javascript" src="../src/xtml/xtml.js"></script>');
document.write('<script type="text/javascript" src="../src/xtml/xtml_usage.js"></script>');
document.write('<script type="text/javascript" src="../src/aaeditor/field_dt.js"></script>');
document.write('<script type="text/javascript" src="../src/aaeditor/edit_mode.js"></script>');
document.write('<script type="text/javascript" src="../src/gstudio/gstudio.js"></script>');
document.write('<script type="text/javascript" src="../src/crawler/crawler.js"></script>');
document.write('<script type="text/javascript" src="../src/crawler/crawler_studio.js"></script>');
document.write('<script type="text/javascript" src="../src/gstudio/studio_data_view.js"></script>');
document.write('<script type="text/javascript" src="../src/jbartapp/instance_editor.js"></script>');
document.write('<script type="text/javascript" src="../src/aaeditor/css_dt.js"></script>');
document.write('<script type="text/javascript" src="../src/aaeditor/css_dt2.js"></script>');
document.write('<script type="text/javascript" src="../src/aaeditor/xtml_dt.js"></script>');
document.write('<script type="text/javascript" src="../src/aaeditor/xtml_dt2.js"></script>');
document.write('<script type="text/javascript" src="../src/aaeditor/xtml_dt_tree.js"></script>');
document.write('<script type="text/javascript" src="../src/aaeditor/aaeditor.js"></script>');
document.write('<script type="text/javascript" src="../src/studio/studio.js"></script>');
document.write('<script type="text/javascript" src="../src/studio/primitive_editor.js"></script>');
document.write('<script type="text/javascript" src="../src/aaeditor/preview_context.js"></script>');
document.write('<script type="text/javascript" src="../src/server/server.js"></script>');
document.write('<script type="text/javascript" src="../src/server/server_usage.js"></script>');
document.write('<script type="text/javascript" src="../src/uiaction/uiaction.js"></script>');
document.write('<script type="text/javascript" src="../src/uiaction/uiaction_usage.js"></script>');
document.write('<script type="text/javascript" src="../src/xmlui/xmlui.js"></script>');
document.write('<script type="text/javascript" src="../src/xmlui/xmlui_usage.js"></script>');
document.write('<script type="text/javascript" src="../src/aaeditor/tree_usage.js"></script>');
document.write('<script type="text/javascript" src="../src/jbart/action.js"></script>');
document.write('<script type="text/javascript" src="../src/jbart/dialog.js"></script>');
document.write('<script type="text/javascript" src="../src/jbart/app_features.js"></script>');
document.write('<script type="text/javascript" src="../src/async/async.js"></script>');
document.write('<script type="text/javascript" src="../src/async/http.js"></script>');
document.write('<script type="text/javascript" src="../src/ui/ui_async.js"></script>');
document.write('<script type="text/javascript" src="../src/bart/bart_utils.js"></script>');
document.write('<script type="text/javascript" src="../src/chart/chart.js"></script>');
document.write('<script type="text/javascript" src="../src/jbart/gcs.js"></script>');
document.write('<script type="text/javascript" src="../src/jbart/jbart_ui.js"></script>');
document.write('<script type="text/javascript" src="../src/jbart/jbart_field.js"></script>'); 
document.write('<script type="text/javascript" src="../src/jbart/jbartdb.js"></script>'); 
document.write('<script type="text/javascript" src="../src/jbart/jbart_utils.js"></script>'); 
document.write('<script type="text/javascript" src="../src/jbart/jbart_api.js"></script>');
document.write('<script type="text/javascript" src="../src/jbart/styles.js"></script>');
document.write('<script type="text/javascript" src="../src/jbart/pref_storage.js"></script>');
document.write('<script type="text/javascript" src="../src/control/controls.js"></script>');
document.write('<script type="text/javascript" src="../src/control/button.js"></script>');
document.write('<script type="text/javascript" src="../src/control/expandable_section.js"></script>');
document.write('<script type="text/javascript" src="../src/control/tabcontrol.js"></script>');
document.write('<script type="text/javascript" src="../src/jbart/mobile.js"></script>'); 
document.write('<script type="text/javascript" src="../src/multilang/multilang.js"></script>');
document.write('<script type="text/javascript" src="../src/googledrive/google_drive.js"></script>'); 
document.write('<script type="text/javascript" src="../src/google_gcs/google_gcs.js"></script>'); 
document.write('<script type="text/javascript" src="lib/jsmin/fulljsmin.js"></script>'); 
document.write('<script type="text/javascript" src="../src/social/social.js"></script>');
document.write('<script type="text/javascript" src="../src/youtube/youtube.js"></script>');
document.write('<script type="text/javascript" src="../src/parser/parser.js"></script>');
document.write('<script type="text/javascript" src="../src/inteliChoice/inteliChoice.js"></script>');
document.write('<script type="text/javascript" src="../src/deprecated/deprecated.js"></script>');
document.write('<script type="text/javascript" src="../src/extjs/extjs.js"></script>');
document.write('<script type="text/javascript" src="../src/cobrowse/cobrowse.js"></script>');
document.write('<script type="text/javascript" src="../src/cobrowse/cobrowse_merge.js"></script>');
document.write('<script type="text/javascript" src="../src/R/r.js"></script>');
document.write('<script type="text/javascript" src="../src/wcf/wcf.js"></script>');
document.write('<script type="text/javascript" src="../src/wrapped_libs/accounting.js"></script>');
document.write('<script type="text/javascript" src="../src/wrapped_libs/moment.js"></script>');

document.write('<script type="text/javascript" src="../bower_components/codemirror/lib/codemirror.js"></script>');
document.write('<script type="text/javascript" src="../bower_components/codemirror/mode/xml/xml.js"></script>');
document.write('<script type="text/javascript" src="../bower_components/codemirror/mode/javascript/javascript.js"></script>');
document.write('<script type="text/javascript" src="../bower_components/codemirror/mode/css/css.js"></script>');
document.write('<script type="text/javascript" src="../bower_components/codemirror/mode/htmlmixed/htmlmixed.js"></script>');
document.write('<script type="text/javascript" src="../bower_components/codemirror/addon/hint/show-hint.js"></script>');
document.write('<script type="text/javascript" src="../bower_components/codemirror/addon/hint/javascript-hint.js"></script>');
document.write('<script type="text/javascript" src="../bower_components/codemirror/addon/hint/xml-hint.js"></script>');
document.write('<script type="text/javascript" src="../bower_components/codemirror/addon/hint/html-hint.js"></script>');
document.write('<script type="text/javascript" src="../bower_components/codemirror/addon/fold/foldgutter.js"></script>');

document.write('<script type="text/javascript" src="../bower_components/moment/moment.js"></script>');

document.write('<script type="text/javascript" src="../bower_components/js-beautify/js/lib/beautify.js"></script>');
document.write('<script type="text/javascript" src="../bower_components/js-beautify/js/lib/beautify-css.js"></script>');
document.write('<script type="text/javascript" src="../bower_components/js-beautify/js/lib/beautify-html.js"></script>');

document.write('<script type="text/javascript" src="../bower_components/jscolor/jscolor.js"></script>');
document.write('<script>jscolor.dir = "../bower_components/jscolor/";</script>');

if (!window.location.href.match(/nodefaultcss/))
	document.write('<link rel="stylesheet" type="text/css" href="default.css?ver=ART_NOW" />'); 
document.write('<link rel="stylesheet" type="text/css" href="jbartStudio.css?ver=ART_NOW" />');
document.write('<link rel="stylesheet" type="text/css" href="lib/treeview/jquery.treeview.css" />'); 
document.write('<link rel="stylesheet" type="text/css" href="../bower_components/codemirror/lib/codemirror.css" />'); 
document.write('<link rel="stylesheet" type="text/css" href="../bower_components/codemirror/theme/solarized.css" />'); 
document.write('<link rel="stylesheet" type="text/css" href="../bower_components/codemirror/addon/fold/foldgutter.css" />'); 
document.write('<link rel="stylesheet" type="text/css" href="../bower_components/codemirror/addon/hint/show-hint.css" />'); 
